In [2]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when 
increasing is False, the i-th output column is the input vector raised element-wise to the power 
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [3]:
def vander_matrix(ip, n, increasing=False):
    
    if not increasing:
        return np.array([[x**(n-i-1) for i in range(n)] for x in ip]).reshape(len(ip),n)
    else:
        return np.array([[x**i for i in range(n)] for x in ip]).reshape(len(ip),n)
        
        
ip_vec = [1,2,3,4,5]
n = 4
print("Vander matrix with Decreasing order of powers\n")
print(vander_matrix(ip_vec,n))

Vander matrix with Decreasing order of powers

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [4]:
print("Vander matrix with Increasing order of powers\n")
print(vander_matrix(ip_vec,n,True))

Vander matrix with Increasing order of powers

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of 
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100 

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values

In [11]:
def movavg(l,k):
    
    n = len(l)
    mv = []
    
    for i in range(n-k+1):
        mv.append(sum(l[i:i+k])/k)
        
    return mv

In [12]:
movavg([10,20,30,40,50,60,70,80,90,100],4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

In [13]:
movavg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]